// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package ai

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
	order "github.com/naskids/nas-mall/rpc_gen/kitex_gen/order"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *QueryOrderRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_QueryOrderRequest[number], err)
}

func (x *QueryOrderRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserMessage, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SimulateAutoOrderRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SimulateAutoOrderRequest[number], err)
}

func (x *SimulateAutoOrderRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserMessage, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SimulateAutoOrderResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SimulateAutoOrderResponse[number], err)
}

func (x *SimulateAutoOrderResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.AssistantMessage, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *QueryOrderRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *QueryOrderRequest) fastWriteField1(buf []byte) (offset int) {
	if x.UserMessage == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetUserMessage())
	return offset
}

func (x *SimulateAutoOrderRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *SimulateAutoOrderRequest) fastWriteField1(buf []byte) (offset int) {
	if x.UserMessage == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetUserMessage())
	return offset
}

func (x *SimulateAutoOrderResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *SimulateAutoOrderResponse) fastWriteField1(buf []byte) (offset int) {
	if x.AssistantMessage == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetAssistantMessage())
	return offset
}

func (x *QueryOrderRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *QueryOrderRequest) sizeField1() (n int) {
	if x.UserMessage == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetUserMessage())
	return n
}

func (x *SimulateAutoOrderRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *SimulateAutoOrderRequest) sizeField1() (n int) {
	if x.UserMessage == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetUserMessage())
	return n
}

func (x *SimulateAutoOrderResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *SimulateAutoOrderResponse) sizeField1() (n int) {
	if x.AssistantMessage == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetAssistantMessage())
	return n
}

var fieldIDToName_QueryOrderRequest = map[int32]string{
	1: "UserMessage",
}

var fieldIDToName_SimulateAutoOrderRequest = map[int32]string{
	1: "UserMessage",
}

var fieldIDToName_SimulateAutoOrderResponse = map[int32]string{
	1: "AssistantMessage",
}

var _ = order.File_order_proto
