// Code generated by Kitex v0.9.1. DO NOT EDIT.

package aimodelservice

import (
	"context"
	"errors"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	ai "github.com/naskids/nas-mall/rpc_gen/kitex_gen/ai"
	order "github.com/naskids/nas-mall/rpc_gen/kitex_gen/order"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"QueryOrder": kitex.NewMethodInfo(
		queryOrderHandler,
		newQueryOrderArgs,
		newQueryOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SimulateAutoOrder": kitex.NewMethodInfo(
		simulateAutoOrderHandler,
		newSimulateAutoOrderArgs,
		newSimulateAutoOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
}

var (
	aiModelServiceServiceInfo                = NewServiceInfo()
	aiModelServiceServiceInfoForClient       = NewServiceInfoForClient()
	aiModelServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aiModelServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aiModelServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aiModelServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AiModelService"
	handlerType := (*ai.AiModelService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ai",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func queryOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(ai.QueryOrderRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ai.AiModelService).QueryOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *QueryOrderArgs:
		success, err := handler.(ai.AiModelService).QueryOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newQueryOrderArgs() interface{} {
	return &QueryOrderArgs{}
}

func newQueryOrderResult() interface{} {
	return &QueryOrderResult{}
}

type QueryOrderArgs struct {
	Req *ai.QueryOrderRequest
}

func (p *QueryOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(ai.QueryOrderRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *QueryOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *QueryOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *QueryOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *QueryOrderArgs) Unmarshal(in []byte) error {
	msg := new(ai.QueryOrderRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryOrderArgs_Req_DEFAULT *ai.QueryOrderRequest

func (p *QueryOrderArgs) GetReq() *ai.QueryOrderRequest {
	if !p.IsSetReq() {
		return QueryOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QueryOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type QueryOrderResult struct {
	Success *order.ListOrderResp
}

var QueryOrderResult_Success_DEFAULT *order.ListOrderResp

func (p *QueryOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(order.ListOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *QueryOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *QueryOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *QueryOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *QueryOrderResult) Unmarshal(in []byte) error {
	msg := new(order.ListOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryOrderResult) GetSuccess() *order.ListOrderResp {
	if !p.IsSetSuccess() {
		return QueryOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*order.ListOrderResp)
}

func (p *QueryOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QueryOrderResult) GetResult() interface{} {
	return p.Success
}

func simulateAutoOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &aiModelServiceSimulateAutoOrderServer{st}
	req := new(ai.SimulateAutoOrderRequest)
	if err := st.RecvMsg(req); err != nil {
		return err
	}
	return handler.(ai.AiModelService).SimulateAutoOrder(req, stream)
}

type aiModelServiceSimulateAutoOrderClient struct {
	streaming.Stream
}

func (x *aiModelServiceSimulateAutoOrderClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *aiModelServiceSimulateAutoOrderClient) Recv() (*ai.SimulateAutoOrderResponse, error) {
	m := new(ai.SimulateAutoOrderResponse)
	return m, x.Stream.RecvMsg(m)
}

type aiModelServiceSimulateAutoOrderServer struct {
	streaming.Stream
}

func (x *aiModelServiceSimulateAutoOrderServer) Send(m *ai.SimulateAutoOrderResponse) error {
	return x.Stream.SendMsg(m)
}

func newSimulateAutoOrderArgs() interface{} {
	return &SimulateAutoOrderArgs{}
}

func newSimulateAutoOrderResult() interface{} {
	return &SimulateAutoOrderResult{}
}

type SimulateAutoOrderArgs struct {
	Req *ai.SimulateAutoOrderRequest
}

func (p *SimulateAutoOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(ai.SimulateAutoOrderRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SimulateAutoOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SimulateAutoOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SimulateAutoOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SimulateAutoOrderArgs) Unmarshal(in []byte) error {
	msg := new(ai.SimulateAutoOrderRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SimulateAutoOrderArgs_Req_DEFAULT *ai.SimulateAutoOrderRequest

func (p *SimulateAutoOrderArgs) GetReq() *ai.SimulateAutoOrderRequest {
	if !p.IsSetReq() {
		return SimulateAutoOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SimulateAutoOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SimulateAutoOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SimulateAutoOrderResult struct {
	Success *ai.SimulateAutoOrderResponse
}

var SimulateAutoOrderResult_Success_DEFAULT *ai.SimulateAutoOrderResponse

func (p *SimulateAutoOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(ai.SimulateAutoOrderResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SimulateAutoOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SimulateAutoOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SimulateAutoOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SimulateAutoOrderResult) Unmarshal(in []byte) error {
	msg := new(ai.SimulateAutoOrderResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SimulateAutoOrderResult) GetSuccess() *ai.SimulateAutoOrderResponse {
	if !p.IsSetSuccess() {
		return SimulateAutoOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SimulateAutoOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.SimulateAutoOrderResponse)
}

func (p *SimulateAutoOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SimulateAutoOrderResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) QueryOrder(ctx context.Context, Req *ai.QueryOrderRequest) (r *order.ListOrderResp, err error) {
	var _args QueryOrderArgs
	_args.Req = Req
	var _result QueryOrderResult
	if err = p.c.Call(ctx, "QueryOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SimulateAutoOrder(ctx context.Context, req *ai.SimulateAutoOrderRequest) (AiModelService_SimulateAutoOrderClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "SimulateAutoOrder", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &aiModelServiceSimulateAutoOrderClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}
