// Code generated by Kitex v0.9.1. DO NOT EDIT.

package aimodelservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/client/callopt/streamcall"
	"github.com/cloudwego/kitex/client/streamclient"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
	ai "github.com/naskids/nas-mall/rpc_gen/kitex_gen/ai"
	order "github.com/naskids/nas-mall/rpc_gen/kitex_gen/order"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	QueryOrder(ctx context.Context, Req *ai.QueryOrderRequest, callOptions ...callopt.Option) (r *order.ListOrderResp, err error)
	SimulateAutoOrder(ctx context.Context, Req *ai.SimulateAutoOrderRequest, callOptions ...callopt.Option) (stream AiModelService_SimulateAutoOrderClient, err error)
}

// StreamClient is designed to provide Interface for Streaming APIs.
type StreamClient interface {
	SimulateAutoOrder(ctx context.Context, Req *ai.SimulateAutoOrderRequest, callOptions ...streamcall.Option) (stream AiModelService_SimulateAutoOrderClient, err error)
}

type AiModelService_SimulateAutoOrderClient interface {
	streaming.Stream
	Recv() (*ai.SimulateAutoOrderResponse, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAiModelServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAiModelServiceClient struct {
	*kClient
}

func (p *kAiModelServiceClient) QueryOrder(ctx context.Context, Req *ai.QueryOrderRequest, callOptions ...callopt.Option) (r *order.ListOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryOrder(ctx, Req)
}

func (p *kAiModelServiceClient) SimulateAutoOrder(ctx context.Context, Req *ai.SimulateAutoOrderRequest, callOptions ...callopt.Option) (stream AiModelService_SimulateAutoOrderClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SimulateAutoOrder(ctx, Req)
}

// NewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
func NewStreamClient(destService string, opts ...streamclient.Option) (StreamClient, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))
	options = append(options, client.WithTransportProtocol(transport.GRPC))
	options = append(options, streamclient.GetClientOptions(opts)...)

	kc, err := client.NewClient(serviceInfoForStreamClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAiModelServiceStreamClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
// It panics if any error occurs.
func MustNewStreamClient(destService string, opts ...streamclient.Option) StreamClient {
	kc, err := NewStreamClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAiModelServiceStreamClient struct {
	*kClient
}

func (p *kAiModelServiceStreamClient) SimulateAutoOrder(ctx context.Context, Req *ai.SimulateAutoOrderRequest, callOptions ...streamcall.Option) (stream AiModelService_SimulateAutoOrderClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.SimulateAutoOrder(ctx, Req)
}
